# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "remix-cf-demo-app"
client_id = "04623d2fe360d12f1ee7406404f9b515"
application_url = "http://localhost:8788"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "http://localhost:8788/auth/callback",
  "http://localhost:8788/auth/shopify/callback",
  "http://localhost:8788/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "remix-cloudflare-app-demo.myshopify.com"
